### ISSUE TITLE
Upgrade to the next rustls version and issue a new release

### ISSUE THREAD

**Issue by DemiMarie-parity** [async-rs/async-tls#26]

**Comment by mzabaluev** [comment]
This seems to have been done yesterday. Unfortunately, the release bumped only the patch version, and this has broken some dependent crates (e.g. https://github.com/libp2p/rust-libp2p/issues/1654) because async-tls exposes rustls through its public API.

I suggest re-releasing it as 0.8.0. Next time, please, be more considerate about the breaking nature of such changes.

**Comment by yoshuawuyts** [comment]
Yanked `v0.7.1`, re-published as `v0.8.0`. Thanks for letting us know!
